# This file was generated by GoReleaser. DO NOT EDIT.
class Qrterminal < Formula
  desc "Create and display QR codes on the command line"
  homepage "https://github.com/mdp/qrterminal"
  url "https://github.com/mdp/qrterminal/releases/download/v2.0.1/qrterminal_2.0.1_darwin_x86_64.tar.gz"
  version "2.0.1"
  sha256 "4e3ff7903a39ace358556fc45d0c3b7dec2d33e897fde84fca5afa11d416fe33"

  def install
    bin.install "qrterminal"
  end
end
